name: ca_je_vanka
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

#
# DEPLOYING APP
# 1. `pubspec.yaml` -> Bump version number
# 2. `release_notes.txt` -> Update changelog for all languages
# 3. `default.txt` -> Update changelog for all languages
#

#
# Android
# `cd android/ && fastlane play_store_release`
#
# GitHub Releases
# `cd android/ && fastlane github_release`
#
# iOS
# `cd ios/ && fastlane app_store_release`
#

environment:
  sdk: 3.8.1

dependencies:
  flutter:
    sdk: flutter

  dart_jsonwebtoken: 3.2.0
  dio: 5.8.0+1
  envied: 1.1.1
  fl_chart: 1.0.0
  flutter_animate: 4.5.2
  flutter_swipe_action_cell: 3.1.5
  flutter_timezone: 4.1.1
  geocoding: 4.0.0
  geolocator: 14.0.2
  get_it: 8.0.3
  hive_ce: 2.11.3
  hive_ce_flutter: 2.3.1
  intl: 0.20.2
  latlong2: 0.9.1
  logger: 2.5.0
  permission_handler: 12.0.1
  watch_it: 1.6.5

dev_dependencies:
  build_runner: 2.5.2
  envied_generator: 1.1.1
  hive_ce_generator: 1.9.2

# Run code generation - `dart run build_runner build -d`

flutter:
  uses-material-design: true

  assets:
    - assets/close.png
    - assets/delete.png
    - assets/drawer.png
    - assets/key.pem
    - assets/weather/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/ProductSans/ProductSansRegular.ttf
          weight: 500
        - asset: assets/ProductSans/ProductSansBold.ttf
          weight: 700
