name: bonevera
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

#
# DEPLOYING APP
# 1. `pubspec.yaml` -> Bump version number
# 2. `release_notes.txt` -> Update changelog for all languages
# 3. `default.txt` -> Update changelog for all languages
#

#
# Android
# `cd android/ && fastlane play_store_release`
#
# GitHub Releases
# `cd android/ && fastlane github_release`
#
# iOS
# `cd ios/ && fastlane app_store_release`
#

environment:
  sdk: 3.8.1

dependencies:
  flutter:
    sdk: flutter

  dart_jsonwebtoken: 3.2.0
  dio: 5.9.0
  dough: 2.0.0
  envied: 1.2.0
  fl_chart: 1.0.0
  flutter_animate: 4.5.2
  flutter_native_splash: 2.4.6
  flutter_swipe_action_cell: 3.1.5
  flutter_timezone: 4.1.1
  geocoding: 4.0.0
  geolocator: 14.0.2
  get_it: 8.2.0
  hive_ce: 2.11.3
  hive_ce_flutter: 2.3.1
  intl: 0.20.2
  latlong2: 0.9.1
  logger: 2.6.1
  permission_handler: 12.0.1
  watch_it: 1.6.5

dev_dependencies:
  build_runner: 2.6.1
  envied_generator: 1.2.0
  flutter_launcher_icons: 0.14.4
  hive_ce_generator: 1.9.3

dependency_overrides:
  meta: 1.17.0

flutter:
  uses-material-design: true

  assets:
    - assets/arrow.png
    - assets/close.png
    - assets/delete.png
    - assets/drawer.png
    - assets/key.pem
    - assets/icon.png
    - assets/splash_icon.png
    - assets/splash.png
    - assets/weather/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/ProductSans/ProductSansRegular.ttf
          weight: 500
        - asset: assets/ProductSans/ProductSansBold.ttf
          weight: 700

# Run code generation - `dart run build_runner build -d`

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'dart run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  min_sdk_android: 21
  adaptive_icon_background: '#342464'
  adaptive_icon_foreground: 'assets/icon.png'
  web:
    generate: true
    image_path: 'assets/icon.png'
    background_color: '#342464'
    theme_color: '#342464'
  windows:
    generate: true
    image_path: 'assets/icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'dart run flutter_native_splash:create'
flutter_native_splash:
  background_image: 'assets/splash.png'
  background_image_dark: 'assets/splash.png'
  android_12:
    image: 'assets/splash_icon.png'
    color: '#342464'
    image_dark: 'assets/splash_icon.png'
    color_dark: '#342464'
