// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:bonevera/models/location/location.dart';
import 'package:bonevera/models/token/token.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LocationAdapter());
    registerAdapter(TokenAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LocationAdapter());
    registerAdapter(TokenAdapter());
  }
}
