// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:ca_je_vanka/models/token/token.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(TokenAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(TokenAdapter());
  }
}
